name: Deploy Pages
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Playwright Tests
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    if: ${{ !(github.event.workflow_run) || !contains(fromJSON('["skipped", "cancelled"]'), github.event.workflow_run.conclusion) }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Fetch all available Playwright reports
        shell: bash {0}
        env:
          SAVE_PATH: gh-pages/artifacts/e2e-tests
        run: |
          gh run list \
              --branch main  \
              --workflow "Playwright Tests" \
              --json databaseId,displayTitle,status,headSha \
          | jq -c '.[]' \
          | while read object; do
              databaseId=$(echo "$object" | jq -r '.databaseId')
              displayTitle=$(echo "$object" | jq -r '.displayTitle')
              status=$(echo "$object" | jq -r '.status')
              headSha=$(echo "$object" | jq -r '.headSha')

              filename=$(echo "run:${databaseId}-sha:${headSha:0:7}-status:${status}-title:${displayTitle}" | sed -E 's/[^[:alnum:]_-]/_/g; s/ +/_/g')
              directory="${SAVE_PATH}/${filename:0:60}"

              echo $directory
              gh run download "$databaseId" -D "$directory" -n playwright-report &
          done
          wait
      - name: Generate index for artifacts
        working-directory: ./gh-pages/artifacts
        run: tree -L 2 -P '**/' -r -H . -T artifacts -o index.html
      - name: Upload GH Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: gh-pages

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
